steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - "-t"
      - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:$SHORT_SHA"
      - "."

  # Step 2: Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:$SHORT_SHA"

  # Step 3: Tag latest
  - name: "gcr.io/cloud-builders/docker"
    args:
      - tag
      - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:$SHORT_SHA"
      - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:latest"

  # Step 4: Push latest tag
  - name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:latest"

  # Step 5: Update Kubernetes YAML image
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - -c
      - |
        sed -i "s|image: asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:.*|image: asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:$SHORT_SHA|g" k8s/deployment-svc.yaml

  # Step 6: Commit & push to GitHub (USING SUBSTITUTIONS)
  - name: "gcr.io/cloud-builders/git"
    entrypoint: bash
    args:
      - -c
      - |
        git config --global user.email "cloudbuild@google.com"
        git config --global user.name "cloudbuild"

        git checkout -B main

        git add k8s/deployment-svc.yaml
        git commit -m "Update image to $SHORT_SHA [skip ci]" || echo "No changes to commit"

        # 🔐 Inject GitHub credentials from Trigger substitutions
        git remote set-url origin https://$_GITHUB_USER:$_GITHUB_TOKEN@github.com/vamshireddy903/gitops-argocd.git

        git push origin main

images:
  - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:$SHORT_SHA"
  - "asia-south1-docker.pkg.dev/test-vamshi/argocd-repo/gitops-dashboard:latest"

options:
  logging: CLOUD_LOGGING_ONLY
